derivative for wigner, example of equivariance check
mariogeiger/se3cnn pull request #24
Opened 2019-08-23 18:54 UTC by machism0

Hopefully you like it!

2019-08-23 22:38 UTC, mariogeiger commented
Isn't `ph.derivative_rot_mat` returning 3 matrices? The derivative wrt alpha, wrt beta and wrt gamma?
if so, don't you also want to return 3 tensors?

2019-09-04 15:52 UTC, machism0 commented
I updated it to return a 3-triple of tensors: dDda, dDdb, dDdc.
Does that solve it?

2019-09-04 16:06 UTC, machism0 commented
There is also the equivariance check. Perhaps we should wait to merge until we update the equivariance check readme.

2019-09-04 19:40 UTC, machism0 commented
I added the equivariance check for the rotation case. Still need to do the parity one.

2019-09-05 05:59 UTC, mariogeiger commented
Thanks Ben, shall I wait the parity test before merge?

2019-09-06 22:28 UTC, machism0 commented
Added a fix for #26.
Changed how spherical_harmonics_xyz is calculated.

2019-09-06 22:30 UTC, machism0 commented
> Thanks Ben, shall I wait the parity test before merge?

Hmm not sure. I am feeling pretty lazy about writing that right now, but I think there are other good fixes in here. I should have separated them.

2019-09-07 06:44 UTC, mariogeiger commented
The `.cpu()` is not necessary.
About the `.detach()` I don’t think we should put it here. 
It’s an informative error for the user that the gradient cannot be computer. 
Moreover if the user changes the default sh by a backwardable one then we don’t want the `.detach()`. 
As a user you can do what you did by doing `sh=lambda x: sh(x.detach())` as argument of Kernel.

2019-09-11 19:54 UTC, machism0 commented
Alright. I vote that it's ready if you think it is. Please accept the pull or let me know what I should change.

2019-09-11 20:49 UTC, mariogeiger requested changes
for me it looks like `examples/point/equivariance.py` should be put into the test files and use the same format as the other files in this directory.

2019-09-11 20:53 UTC, mariogeiger commented on se3cnn/point/kernel.py
> +            raise TypeError("The r input of kernel cannot require a gradient.")
You cannot do that. Someone might want to allow `r` to require grad if he uses its own `sh` function.
Why do you want to do that? Is it the current error message that is not clear enough?

2019-09-12 16:53 UTC, bkmi commented on se3cnn/point/kernel.py
> +            raise TypeError("The r input of kernel cannot require a gradient.")
It was for clarity, but I'm okay with leaving it how it is:

```python
Traceback (most recent call last):
  File "/Users/user/miniconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-c6f6414c7b04>", line 1, in <module>
    runfile('/Users/user/sci/cgae/otp_equi.py', wdir='/Users/user/sci/cgae')
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/user/sci/cgae/otp_equi.py", line 223, in <module>
    main()
  File "/Users/user/sci/cgae/otp_equi.py", line 215, in main
    results = execute(args)
  File "/Users/user/sci/cgae/otp_equi.py", line 114, in execute
    pred_sph = decoder(cg_features, cg_xyz)
  File "/Users/user/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/user/sci/cgae/cgae/equi.py", line 89, in forward
    output = layer(output.div(geometry.size(1) ** 0.5), geometry)  # Normalization of layers by number of atoms.
  File "/Users/user/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/user/sci/se3cnn/se3cnn/non_linearities/gated_block.py", line 41, in forward
    features = self.op(*args, **kwargs)  # [..., channel, ...]
  File "/Users/user/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/user/sci/se3cnn/se3cnn/point/operations.py", line 19, in forward
    k = self.kernel(rb - ra)  # [batch, a, b, i, j]
  File "/Users/user/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/user/sci/se3cnn/se3cnn/point/kernel.py", line 120, in forward
    Ys = self.sh(self.set_of_l_filters, r)  # [l_filter * m_filter, batch]
  File "/Users/user/sci/se3cnn/se3cnn/SO3.py", line 304, in spherical_harmonics_xyz
    out = spherical_harmonics(order, alpha, beta)  # [m, ...]
  File "/Users/user/sci/se3cnn/se3cnn/SO3.py", line 274, in spherical_harmonics
    Y = sh(Js, Ms, math.pi - beta.cpu().numpy(), alpha.cpu().numpy())
RuntimeError: Can't call numpy() on Variable that requires grad. Use var.detach().numpy() instead.
```

2019-09-17 17:47 UTC, bkmi commented
> for me it looks like `examples/point/equivariance.py` should be put into the test files and use the same format as the other files in this directory.

I though the purpose of this file was so that a user would have a minimum example to learn how to test equivariance. I'm happy to put it in test, and will do so, but I think there must be some kind of note in the readme letting the user know about it. I would never read the tests as a user.

2019-09-18 07:41 UTC, mariogeiger commented
Ok I agree it makes sense

2019-09-18 07:42 UTC, merged