Allow `DataParallel` and `jit.trace`
mariogeiger/se3cnn pull request #4
Opened 2018-10-17 15:30 UTC by jatentaki

1. Changed some tensors which used to be updated with in-place sliced mutation to instead concatenate lists of temporary results. This may have resulted in some increase of memory footprint, but the previous code was technically UB from the perspective of autograd (as far as I understand the documentation and pytorchers on slack), so now it plays nicely with `nn.DataParallel` and `jit.trace`.
2. Reorganized the tests, moved to top-level `tests` directory. The `all` runner script is ugly, but I couldn't get `python -m unittest discover` to work. Also note that `all` runs all tests in the directory, not all in the whole project
3. Lowered the memory footprint of batchnorm slightly by detaching a variable earlier.

Hopefully the commit messages are more descriptive of particular modifications. I tried to test this under `0.4.1` and `1.0 preview`, but please test this yourself before merging

2018-10-17 15:53 UTC, mariogeiger requested changes
Be careful, `field_mean` and `field_norm` are used later to normalize the fields.
We need the gradient to go trough them !

I think this modification is not good.

2018-10-17 16:03 UTC, mariogeiger requested changes

2018-10-17 16:03 UTC, mariogeiger commented on se3cnn/kernel.py
> +                    ker = torch.tensor(0.)
Please always use things like `weight.new_tensor` to ensure have the same `device` and `dtype`.
Then I think you cannot apply `view` on it. At least `torch.tensor(0.).view(2, 2)` crash on my computer.

2018-10-17 16:08 UTC, mariogeiger requested changes
Looks super cool. If jit works it's amazing.

Please test also the gradients. Please compare your implementation output+gradient with the current version. They must match.

2018-10-17 16:14 UTC, mariogeiger commented on se3cnn/kernel.py
> +                    ker = torch.tensor(0.)
You could add a test that has at least one `kij is None`.
`se3cnn.kernel.SE3Kernel([(1, 0)], [(1, 0), (1, 5)], 3)` does the trick

2018-10-17 16:16 UTC, mariogeiger commented
I see that some code with `dyn_iso` is removed. Is it because you don't have the last commits from master ? I don't know if I have to worry about that or if it will be managed during merge.

2018-10-18 10:06 UTC, jatentaki commented
I addressed most issues
1) The gradient indeed needs to flow there, fixed. Additionally, I added gradtests for both `SE3BatchNorm` and `SEBNConv`. The former passes, the latter fails due to what appears to numerical errors. Note that it also fails with the original implementation (current master). Do you have any idea how to address that?
2) Can you think of a better way to test correctness than to compare with the old version? It feels awkward to keep both for this purpose, plus realistically the older version is also not guaranteed to be bug-free. I would rather trust some actual sanity checks. Checking for equivariance follows this line of thought, but I agree more tests would be useful.
3) Fixed the `kij is None` issue. I did not use `new_tensor` but `torch.zeros(..., device=old.device, dtype=old.dtype)`, which effectively does the same thing.
4) I have no what this `dyn_iso` thing is, I have never touched it. I am trying to figure out how to pull your upstream changes to my fork.

2018-10-18 13:04 UTC, mariogeiger reviewed
If you want to check the derivative of BN you can also check with a very simple test vs hand calculus:
```python
x = torch.rand(3, requires_grad=True).view(1, 3, 1, 1, 1)
bn = se3cnn.SE3BatchNorm([(1, 3)], eps=0)
y = bn(x)

# by hand dyi/dxj = delta_ij / |x| - xi xj / |x|^3

jac_num = jacobian(y, x)  # github.com/mariogeiger/hessian
jac_cal = torch.eye(3) / x.norm() - x.view(-1, 1) * x.view(1, -1) / x.norm() ** 3

assert jac_cal == jac_num
```

For simplicity I took `eps=0` but one could also consider it into the calculus as well.

2018-10-18 13:04 UTC, mariogeiger commented on tests/batchnorm_tests.py
> +        self.assertTrue(torch.autograd.gradcheck(conv, (x, ), eps=1))
It is not a linear function so it should not work with `eps=1`, did you try with a smaller value ?

2018-10-18 13:04 UTC, mariogeiger commented on tests/batchnorm_tests.py
> +        self.assertTrue(torch.autograd.gradcheck(bn, (x, ), eps=1))
Same here, `y = x / sqrt(var(x))` is nonlinear therefore `eps` should be small

2018-10-24 09:07 UTC, merged